version: '3.8'

services:
  api:
    container_name: container-api
    image: php8apache
    restart: always
    build: ./api/docker
    volumes:
      - ./api/src:/var/www/html
    ports:
      - 8000:80