version: '3.8'

services:
  api:
    container_name: container-api
    image: app-menu-api
    restart: always
    build: ./api/docker
    volumes:
      - ./api/src:/var/www
    ports:
      - 9000:80
    # command: composer install
